adminUser:
  password: local:jenkinsx/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: abhibroto04@gmail.com
  token: local:jenkinsx/pipelineUser:token
  username: abhiBotMukherjee
prow:
  hmacToken: local:jenkinsx/prow:hmacToken
